name: Go
on:
  push:
    branches:
      - "**/*"
    tags:
      - "!*"
  pull_request:
    branches:
      - "**/*"
    tags:
      - "!*"

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: checkout
        uses: actions/checkout@v3

      - name: test
        run: |
          make clean test all
