name: Go
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true

      - name: test
        run: |
          GORELEASER_CMD=$(which goreleaser) make clean test all
